import { createClient } from "@supabase/supabase-js";

export const supabase=createClient("https://rsfryrxxhqbwzlrqnuco.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZnJ5cnh4aHFid3pscnFudWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODc5MTYsImV4cCI6MjA2NTk2MzkxNn0.PANHyy3x-ce7sPuq2XRXGQmt9uCM1kLKSlZHXrL9SX4")